version: '3.9'

services:
  api:
    container_name: minjot_api
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
    env_file:
      - .env
    volumes:
      - "${PWD}:/opt/app"
    ports:
      - "9090:9090"
    networks:
      - internal-net

  database:
    platform: linux/amd64
    image: postgis/postgis:13-3.3-alpine
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./docker_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "9630:5432"
    networks:
      - internal-net

volumes:
  docker_data:


networks:
  internal-net:
    name: backend_network
