name: CI/CD | Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Pylint Code Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyze the code with Pylint
        run: pylint $(git ls-files '*.py') || exit 0